
modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="sensation"
version="${file.jarVersion}"
displayName="Sensation"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="sensation.png"
credits="Thanks for this mod goes to Zoey the Egoist"
authors="AvocadoSpud, Sarinsa, Eltrutlikes"
description="Improving Minecraft's Game Feel"
license="MIT"

[[dependencies.sensation]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sensation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
